version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - cd front
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: front
  files:
    - .next/**/*
    - public/**/*
    - package.json
    - next.config.js
    - appspec.yml
    - scripts/**/*