version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - cd front
      - npm ci

  build:
    commands:
      #- export NEXT_PUBLIC_API_BASE_URL=http://10.0.2.205:8080/api
      #- export BACKEND_URL=http://10.0.2.205:8080/api
      - npm run build

artifacts:
  base-directory: front
  files:
    - .next/**/*
    - public/**/*
    - appspec.yml
    - scripts/**/*
    - package.json
    - node_modules/**/*
